### PR TITLE
Implemented CyberNewsDB from scratch.

### PR DESCRIPTION
**Pull request by hardik1408**
Modified the way data is obtained from the web. 

## Description

`cybernews` is no longer required as a python dependency. The code has been implemented from scratch, with some modifications. The extra websited which were scrapping reduntant data, such as that for the categories like social media, buisness etc were all unnecessary for our project. So, they have been removed completely.
## Motivation and Context

When we imported `cybernews` as a python package, we could not make any changes as to how the data was being scrapped and appended in the database. Now that we have implemented it from scratch, it gives us the ability make necessary modifications in the process and change the way data is being received and modified.

## Screenshots (if appropriate):
Screenshot_20240613_213342
The above screenshot displays data being collected successfully.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by CoToYo — APPROVED** [review]
It looks like code under `utils` folder are solely for `cybernews`. Can we move `utils` under `cybernews`?
@hardik1408

**Comment by hardik1408** [comment]
> It looks like code under `utils` folder are solely for `cybernews`. Can we move `utils` under `cybernews`? @hardik1408

Alright

**Comment by hardik1408** [comment]
@CoToYo Made some changes, kindly review

**Review by CoToYo — COMMENTED** [review]
Can we remove the two `__pycache__` folder? Not sure what do they do.

**Comment by hardik1408** [comment]
They are automatically generated upon running the code.

**Comment by CoToYo** [comment]
> They are automatically generated upon running the code.

then we can ignore them by putting them into `git .ignore`. we may only commit necessary code here.

**Comment by hardik1408** [comment]
> > They are automatically generated upon running the code.
> 
> then we can ignore them by putting them into `git .ignore`. we may only commit necessary code here.

Alright, I will do the changes

**Comment by hardik1408** [comment]
@CoToYo made the required changes, kindly review

**Pull request merged**
